### ISSUE TITLE
Prototyp EmailClient

### ISSUE THREAD

**Issue by MK-NEUKO** [MK-NEUKO/EmailClientProtoType#1]
@suchja
Hallo Jan, ich habe MailKit gewählt und mein Postfach abgerufen.
Funktioniert soweit, ich werde die nächsten Tage das Senden einer Mail und das Abfragen der erforderlichen Daten in der Console implementieren.
Grüße Michael

**Comment by MK-NEUKO** [comment]
@suchja
Nachdem du deine Serverdaten eingegeben hast und die message im Quelltext entsprechen konfiguriert hast funktioniert es.
Im Programm die Email und Passwort eingeben, dann wird gesendet und danach die Inbox abgerufen.
Ich habe es mit meinem Postfach getestet.

**Comment by suchja** [comment]
@MK-NEUKO Sehr cool! Finde ich wirklich super. 
Darf ich dein Verzeichnis in der nächsten LernMail verlinken? Ich könnte auch einen Fork davon erstellen. Du willst das Verzeichnis ja wahrscheinlich auch irgendwann wieder löschen.

**Comment by MK-NEUKO** [comment]
@suchja
Klar, kein Problem, es ist ja OpenSource 😀.
